# version: "3.8"
# services:
#   db:
#     image: postgres:16
#     container_name: my-postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 226622
#       POSTGRES_DB: mydb
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:

version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: abdullah
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
